USE DE_GUATE_ARTESANIAS_DB;
-- -------------------------------------------------------
-- PROCEDIMIENTO PARA EJECUTAR PROCEDIMIENTOS
-- -------------------------------------------------------
DROP PROCEDURE IF EXISTS EJECUTAR;
DELIMITER $
CREATE PROCEDURE EJECUTAR()
BEGIN

DECLARE i INT DEFAULT 0;

-- Crear empresa por defecto
IF(NOT EXISTS(SELECT EMPRESA FROM EMPRESA))
THEN
	CALL CREAR_EMPRESA('NOMBRE','SOLGAN','MISION','VISION','DESCRIPCION',000000000
						,'DIRECCION','CORREO@CORREO.COM','NOVEDADES');
END IF;

SELECT * FROM EMPRESA;

-- Crear usuaurio Administrador
CALL INSERTAR_ADMIN('admin','admin');

SELECT * FROM ADMINISTRADOR;

-- Insertar Imagenes
IF(NOT EXISTS(SELECT IMAGEN FROM IMAGEN WHERE IMAGEN = -1))
THEN 
CALL IMG_DEFECTO();
END IF;

WHILE i <= 10 DO
      CALL CREAR_IMG(CONCAT('IMAGEN',CAST(i as char(2))),CONCAT('URL',CAST(i as char(2)))); 
      SET i=i+1;
END WHILE;

SELECT * FROM IMAGEN;

-- Asignar imagenes a empresa
SET i = 1;
WHILE i < 6 DO
	  CASE i
		  WHEN 1 THEN CALL ASIGNAR_IMG_EMPRESA('LOGO',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 2 THEN CALL ASIGNAR_IMG_EMPRESA('PORTADA1',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 3 THEN CALL ASIGNAR_IMG_EMPRESA('PORTADA2',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 4 THEN CALL ASIGNAR_IMG_EMPRESA('PORTADA3',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 5 THEN CALL ASIGNAR_IMG_EMPRESA('NOVEDADES',(SELECT FLOOR(RAND()*9)+1));
      END CASE;
      SET i=i+1;
END WHILE;

SELECT (GET_TIPO(IE.TIPO)),E.NOMBRE,I.URL 
FROM IMG_EMPRESA IE,EMPRESA E,IMAGEN I
WHERE IE.EMPRESA = E.EMPRESA
AND IE.IMAGEN = I.IMAGEN;

-- Actualizar imagenes de empresa
SET i = 1;
WHILE i < 6 DO
	  CASE i
		  WHEN 1 THEN CALL ASIGNAR_IMG_EMPRESA('LOGO',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 2 THEN CALL ASIGNAR_IMG_EMPRESA('PORTADA1',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 3 THEN CALL ASIGNAR_IMG_EMPRESA('PORTADA2',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 4 THEN CALL ASIGNAR_IMG_EMPRESA('PORTADA3',(SELECT FLOOR(RAND()*9)+1));
		  WHEN 5 THEN CALL ASIGNAR_IMG_EMPRESA('NOVEDADES',(SELECT FLOOR(RAND()*9)+1));
      END CASE;
      SET i=i+1;
END WHILE;

SELECT (GET_TIPO(IE.TIPO)),E.NOMBRE,I.URL 
FROM IMG_EMPRESA IE,EMPRESA E,IMAGEN I
WHERE IE.EMPRESA = E.EMPRESA
AND IE.IMAGEN = I.IMAGEN;

-- Actualizar solo el logo
CALL ASIGNAR_IMG_EMPRESA('LOGO',(SELECT FLOOR(RAND()*9)+1));

SELECT IE.TIPO,E.NOMBRE,I.URL 
FROM IMG_EMPRESA IE,EMPRESA E,IMAGEN I
WHERE IE.EMPRESA = E.EMPRESA
AND IE.IMAGEN = I.IMAGEN;

-- Crear Red Social
CALL CREAR_RS('FACEBOOK','WWW.FACEBOOK.COM',(SELECT FLOOR(RAND()*9)+1));
CALL CREAR_RS('TWITER','WWW.TWITER.COM',(SELECT FLOOR(RAND()*9)+1));
SELECT * FROM RED_SOCIAL;

-- Eliminar Red_Social
CALL ELIMINAR_RS(1);
SELECT * FROM RED_SOCIAL;

-- Crear Categorias

IF(NOT EXISTS(SELECT CATEGORIA FROM CATEGORIA WHERE IMAGEN = -1))
THEN 
CALL CAT_DEFECTO();
END IF;

SET i = 0;
WHILE i < 10 DO
	  CALL CREAR_CAT(CONCAT('CAT',CAST(i+1 as char(2))),1+i);
      SET i=i+1;
END WHILE;

SELECT C.NOMBRE,I.URL 
FROM CATEGORIA C,IMAGEN I
WHERE C.IMAGEN = I.IMAGEN;

-- Actualizar Categoria
CALL ACTUALIZAR_CAT('CAT11',10,10);

SELECT C.NOMBRE,I.URL 
FROM CATEGORIA C,IMAGEN I
WHERE C.IMAGEN = I.IMAGEN
AND C.CATEGORIA = 10;

-- Crear Productos
SET i = 0;
WHILE i < 10 DO
	  CALL CREAR_PRODUCTO(CONCAT('PROD',CAST(i as char(2))),'DESCRIPCION',100.00);
      CALL ASIGNAR_IMG_PROD((SELECT FLOOR(RAND()*9)+1),NULL);
      CALL ASIGNAR_CAT_PROD((SELECT FLOOR(RAND()*9)+1),NULL);
      SET i=i+1;
END WHILE;

SELECT P.TITULO,P.DESCRIPCION,P.PRECIO,C.NOMBRE,I.URL
FROM PRODUCTO P,CATEGORIA C,IMAGEN I,PROD_CAT PC, IMG_PROD IP
WHERE P.PRODUCTO = PC.PRODUCTO
AND C.CATEGORIA = PC.CATEGORIA
AND P.PRODUCTO = IP.PRODUCTO
AND I.IMAGEN = IP.IMAGEN
ORDER  BY P.PRODUCTO ASC;

-- Actualizar Productos
START TRANSACTION;
SELECT * FROM PRODUCTO;
CALL ACTUALIZAR_PRODUCTO('PROD100','DESCRIPCION',120.50,1);
CALL ELIMINAR_IMG_PROD(1);
CALL ASIGNAR_IMG_PROD(2,1);
CALL ELIMINAR_CAT_PROD(1);
CALL ASIGNAR_CAT_PROD(2,1);

SELECT P.TITULO,P.DESCRIPCION,P.PRECIO,C.NOMBRE,I.URL
FROM PRODUCTO P,CATEGORIA C,IMAGEN I,PROD_CAT PC, IMG_PROD IP
WHERE P.PRODUCTO = PC.PRODUCTO
AND C.CATEGORIA = PC.CATEGORIA
AND P.PRODUCTO = IP.PRODUCTO
AND I.IMAGEN = IP.IMAGEN
AND P.PRODUCTO = 1;


ROLLBACK;

SELECT P.TITULO,P.DESCRIPCION,P.PRECIO,C.NOMBRE,I.URL
FROM PRODUCTO P,CATEGORIA C,IMAGEN I,PROD_CAT PC, IMG_PROD IP
WHERE P.PRODUCTO = PC.PRODUCTO
AND C.CATEGORIA = PC.CATEGORIA
AND P.PRODUCTO = IP.PRODUCTO
AND I.IMAGEN = IP.IMAGEN
AND P.PRODUCTO = 1;

-- Eliminar Productos
START TRANSACTION;
CALL ELIMINAR_PRODUCTO(2);
COMMIT;

SELECT P.TITULO,P.DESCRIPCION,P.PRECIO,C.NOMBRE,I.URL
FROM PRODUCTO P,CATEGORIA C,IMAGEN I,PROD_CAT PC, IMG_PROD IP
WHERE P.PRODUCTO = PC.PRODUCTO
AND C.CATEGORIA = PC.CATEGORIA
AND P.PRODUCTO = IP.PRODUCTO
AND I.IMAGEN = IP.IMAGEN
AND P.PRODUCTO = 1;

-- Crear Tiendas
SET i = 0;
WHILE i < 10 DO
	  CALL CREAR_TIENDA(CONCAT('TIENDA',CAST(i as CHAR(2))),'DIRECCION',00000000,'WWW.TIENDA.COM',(SELECT FLOOR(RAND()*9)+1));
      SET i=i+1;
END WHILE;

SELECT T.NOMBRE,T.DIRECCION,T.TELEFONO,T.ENLACE,I.URL
FROM TIENDA T,IMAGEN I
WHERE T.IMAGEN = I.IMAGEN
ORDER BY T.TIENDA ASC; 

-- Eliminar Tiendas
CALL ELIMINAR_TIENDA(1);

SELECT T.NOMBRE,T.DIRECCION,T.TELEFONO,T.ENLACE,I.URL
FROM TIENDA T,IMAGEN I
WHERE T.IMAGEN = I.IMAGEN
ORDER BY T.TIENDA ASC; 

-- Crear Marcas
SET i = 0;
WHILE i < 10 DO
	  CALL CREAR_MARCA(CONCAT('MARCA',CAST(i as CHAR(2))),(SELECT FLOOR(RAND()*9)+1),'DESCRIPCION');
      SET i=i+1;
END WHILE;

SELECT M.NOMBRE,I.URL,M.DESCRIPCION
FROM MARCA M,IMAGEN I
WHERE I.IMAGEN = M.IMAGEN
ORDER BY MARCA ASC;

-- Eliminar Marcas
CALL ELIMINAR_MARCA(1);

SELECT M.NOMBRE,I.URL,M.DESCRIPCION
FROM MARCA M,IMAGEN I
WHERE I.IMAGEN = M.IMAGEN
ORDER BY MARCA ASC;

-- Eliminar Imagen
CALL ELIMINAR_IMG(3);

SELECT * FROM IMAGEN;

-- Eliminar Categoria
CALL ELIMINAR_CAT(1);

SELECT * FROM CATEGORIA;

-- Vistas
DROP VIEW IF EXISTS IMAGENES_EMPRESA;
CREATE VIEW IMAGENES_EMPRESA
AS
SELECT I.URL AS IMAGEN, GET_TIPO(IE.TIPO) AS TIPO
FROM IMAGEN I, EMPRESA E, IMG_EMPRESA IE
WHERE I.IMAGEN = IE.IMAGEN
AND E.EMPRESA = IE.EMPRESA;

DROP VIEW IF EXISTS IMAGENES_RS;
CREATE VIEW IMAGENES_RS
AS
SELECT I.URL AS IMAGEN, RS.URL AS LINK, RS.NOMBRE AS RED
FROM IMAGEN I,RED_SOCIAL RS,EMPRESA E
WHERE I.IMAGEN = RS.IMAGEN
AND RS.EMPRESA = E.EMPRESA;

DROP VIEW IF EXISTS PRODUCTOS;
CREATE VIEW PRODUCTOS
AS
SELECT P.TITULO AS PRODUCTO,P.DESCRIPCION AS DESCRIPCION,P.PRECIO AS PRECIO ,C.NOMBRE AS CATEGORIA ,I.URL AS IMAGEN
FROM PRODUCTO P,CATEGORIA C,IMAGEN I,PROD_CAT PC, IMG_PROD IP
WHERE P.PRODUCTO = PC.PRODUCTO
AND C.CATEGORIA = PC.CATEGORIA
AND P.PRODUCTO = IP.PRODUCTO
AND I.IMAGEN = IP.IMAGEN
ORDER  BY P.PRODUCTO ASC;

SELECT *
FROM PRODUCTOS P
WHERE P.CATEGORIA IN
					(
						SELECT C.NOMBRE
						FROM CATEGORIA C
						WHERE C.NOMBRE = 'CAT2'
					);
                    
CALL CAMBIAR_NOMBRE('DE GUATE');

END $


CALL EJECUTAR();